name: delivery_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_database: ^10.4.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sushi_1.png
    - assets/sushi.png
    - assets/ramen.png
    - assets/pizza.png
    - assets/salad.png
    - assets/hot-soup.png
    - assets/coffee.png
    - assets/drink.png
    - assets/sashimi.png

